server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
  application:
    name: User-Service
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8086
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZONE: http://localhost:8761/eureka